language: generic 
sudo: required
services:
  - docker


before_install:
  - docker build -t devshubham1/docker-react-sample -f Dockerfile.dev .

scripts:
  - docker run -e CI=true devshubham1/docker-react-sample npm run test

